version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8080:80"  # Exposing port 80 from the container (Nginx will listen here)
    volumes:
      - .:/var/www
    networks:
      - laravel_network
    # Nginx will handle the routing, no need for "php artisan serve"
    
networks:
  laravel_network:
    driver: bridge

