version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
      - ./.env:/var/www/.env
    networks:
      - laravel_network
    working_dir: /var/www

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  redis:
    image: redis:latest
    container_name: laravel_redis
    networks:
      - laravel_network

  memcached:
    image: memcached:latest
    container_name: laravel_memcached
    networks:
      - laravel_network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
